version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd yash-sa2-etl-pipeline
      - mvn clean 
      - mvn install
     
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
     - yash-sa2-etl-pipeline/target/yash-sa2-etl-pipeline-0.0.1-SNAPSHOT.jar
  #discard-paths: yes
